name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          USERNAME: deploy
          HOST: inform.focusworks.dev
          PROJECT_SIGNING_SALT: ${{ secrets.PROJECT_SIGNING_SALT }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          PROJECT_PORT: ${{ secrets.PROJECT_PORT }}
          MIX_ENV: prod
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/deploy/inform
            scripts/deploy.sh
            

